workspace(name = "up_and_running")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Go rules

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "b9aa86ec08a292b97ec4591cf578e020b35f98e12173bbd4a921f84f583aebd9",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
    ],
)

# Gazelle is a tool for auto-creating BUILD.bazel files for Go
# projects ("bazel run //:gazelle"). It provides a "happy path"
# for Go projects - the BUILD files you see here were generated
# by Gazelle, not by hand.

http_archive(
    name = "bazel_gazelle",
    sha256 = "86c6d481b3f7aedc1d60c1c211c6f76da282ae197c3b3160f54bd3a8f847896f",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.1/bazel-gazelle-v0.19.1.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.1/bazel-gazelle-v0.19.1.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(
    go_version = "1.13.4",  # Defaults to latest
)

# tip:
# bazel build @io_bazel_rules_go//:go_info
# cat bazel-bin/external/io_bazel_rules_go/darwin_amd64_stripped/go_info%/go_info_report
# Compare to the output of "go version"

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

# Dependencies

# tip:
# bazel run //:gazelle -- update-repos github.com/mattn/go-slim

go_repository(
    name = "com_github_mattn_go_slim",
    importpath = "github.com/mattn/go-slim",
    sum = "h1:GF43XHtQ/ewS07mITQZyi9gXhWZ7x7crGWp2hvHUEkM=",
    version = "v0.0.0-20190926010428-236f1c35e4e6",
)

# From the rules_go documentation:

# "Note that go build won't be aware of dependencies listed in WORKSPACE,
# so you may want to download your dependencies into your GOPATH or module
# cache so that your tools are aware of them. You may also need to check
# in generated files."

# Thus: go get github.com/mattn/go-slim
